import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

const myFont = localFont({
	src: "../../fonts/BrownSugar.ttf",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
			<NavBar />
				{children}
			</body>
    </html>
  );
}
