import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";

const marcellus = Marcellus({ 
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-marcellus",
 });

const myFont = localFont({
	src: "../../fonts/BrownSugar.ttf",
	variable: "--font-brownSugar",

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} ${marcellus.variable}`}>
			<NavBar />
				{children}
			</body>
    </html>
  );
}
